#pragma once

/* LED auf Basisplatine */
#define LEDGRUEN_PORT PORTD
#define LEDGRUEN_PIN  PIN0_bm
#define LEDROT_PORT PORTD
#define LEDROT_PIN  PIN1_bm

#define LEDGRUENSETUP LEDGRUEN_PORT.DIRSET=LEDGRUEN_PIN
#define LEDGRUEN_ON   LEDGRUEN_PORT.OUTCLR=LEDGRUEN_PIN
#define LEDGRUEN_OFF  LEDGRUEN_PORT.OUTSET=LEDGRUEN_PIN
#define LEDGRUEN_TOGGLE  LEDGRUEN_PORT.OUTTGL=LEDGRUEN_PIN

#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN
#define LEDROT_TOGGLE  LEDROT_PORT.OUTTGL=LEDROT_PIN

#ifdef TASTATUR
#define LEDGRUEN_TAST_PORT PORTB
#define LEDGRUEN_TAST_PIN  PIN3_bm
#define LEDROT_TAST_PORT PORTB
#define LEDROT_TAST_PIN  PIN2_bm

#define LEDGRUEN_TASTSETUP LEDGRUEN_TAST_PORT.DIRSET=LEDGRUEN_TAST_PIN
#define LEDGRUEN_TAST_ON   LEDGRUEN_TAST_PORT.OUTCLR=LEDGRUEN_TAST_PIN
#define LEDGRUEN_TAST_OFF  LEDGRUEN_TAST_PORT.OUTSET=LEDGRUEN_TAST_PIN
#define LEDGRUEN_TAST_TOGGLE  LEDGRUEN_TAST_PORT.OUTTGL=LEDGRUEN_TAST_PIN

#define LEDROT_TASTSETUP LEDROT_TAST_PORT.DIRSET=LEDROT_TAST_PIN
#define LEDROT_TAST_ON   LEDROT_TAST_PORT.OUTCLR=LEDROT_TAST_PIN
#define LEDROT_TAST_OFF  LEDROT_TAST_PORT.OUTSET=LEDROT_TAST_PIN
#define LEDROT_TAST_TOGGLE  LEDROT_TAST_PORT.OUTTGL=LEDROT_TAST_PIN
#endif // TASTATUR



