#pragma once

#define BROADCAST "BR"

#define REPORT_BETWEEN_SENSORS 40
#define REPORT_BETWEEN_BLOCKS  3000
//#define WAIT_AFTER_LAST_SENSOR  300

enum{FIRSTREPORT, ACT_POSITION, SET_POSITION, FIXPOS_A, FIXPOS_B, FIXPOS_C, UPTIME, DOWNTIME, LASTREPORT};

#define TicsPerSecond 123.45679
#define TicsPer10ms   1.2345679
