/*
 * constants.h
 *
 * Created: 24.05.2018 19:24:50
 *  Author: chrak_2
 */


#ifndef MYCONSTANTS_H_
#define MYCONSTANTS_H_

#define BROADCAST "BR"

#define REPORT_BETWEEN_SENSORS 40
#define REPORT_BETWEEN_BLOCKS  3000
//#define WAIT_AFTER_LAST_SENSOR  300

enum{FIRSTREPORT, ACT_POSITION, SET_POSITION, FIXPOS_A, FIXPOS_B, FIXPOS_C, UPTIME, DOWNTIME, LASTREPORT};

#endif /* MYCONSTANTS_H_ */
