#pragma once

#if NUM_ROLLLADEN > 0
  #define ROLL_PORT PORTA
  #ifdef ROLL1_INV
    #define ROLL1_UP_PIN   PIN3_bm
    #define ROLL1_DOWN_PIN PIN6_bm
    #pragma message "Rolladen 1 läuft invers"
  #else
    #define ROLL1_UP_PIN   PIN6_bm
    #define ROLL1_DOWN_PIN PIN3_bm
  #endif // ROLL1_INV
#endif // NUM_ROLLLADEN
#if NUM_ROLLLADEN > 1
  #ifdef ROLL2_INV
    #define ROLL2_UP_PIN PIN2_bm
    #define ROLL2_DOWN_PIN PIN4_bm
    #pragma message "Rolladen 2 läuft invers"
  #else
    #define ROLL2_UP_PIN PIN4_bm
    #define ROLL2_DOWN_PIN PIN2_bm
  #endif // ROLL2_INV
#endif // NUM_ROLLLADEN
#if NUM_ROLLLADEN > 2
  #ifdef ROLL3_INV
    #define ROLL3_UP_PIN PIN1_bm
    #define ROLL3_DOWN_PIN PIN5_bm
    #pragma message "Rolladen 3 läuft invers"
  #else
    #define ROLL3_UP_PIN PIN5_bm
    #define ROLL3_DOWN_PIN PIN1_bm
  #endif // ROLL3_INV
#endif // NUM_ROLLLADEN

#if NUM_ROLLLADEN > 0
  #define ROLL1SETUP  ROLL_PORT.DIRSET=ROLL1_DOWN_PIN | ROLL1_UP_PIN
  #define ROLL1_DOWN  ROLL_PORT.OUTCLR=ROLL1_UP_PIN   ; ROLL_PORT.OUTSET=ROLL1_DOWN_PIN
  #define ROLL1_UP    ROLL_PORT.OUTCLR=ROLL1_DOWN_PIN ; ROLL_PORT.OUTSET=ROLL1_UP_PIN
  #define ROLL1_OFF   ROLL_PORT.OUTCLR=ROLL1_DOWN_PIN ; ROLL_PORT.OUTCLR=ROLL1_UP_PIN
#endif // NUM_ROLLLADEN

#if NUM_ROLLLADEN > 1
  #define ROLL2SETUP  ROLL_PORT.DIRSET=ROLL2_DOWN_PIN | ROLL2_UP_PIN
  #define ROLL2_DOWN  ROLL_PORT.OUTCLR=ROLL2_UP_PIN   ; ROLL_PORT.OUTSET=ROLL2_DOWN_PIN
  #define ROLL2_UP    ROLL_PORT.OUTCLR=ROLL2_DOWN_PIN ; ROLL_PORT.OUTSET=ROLL2_UP_PIN
  #define ROLL2_OFF   ROLL_PORT.OUTCLR=ROLL2_DOWN_PIN ; ROLL_PORT.OUTCLR=ROLL2_UP_PIN
#endif // NUM_ROLLLADEN

#if NUM_ROLLLADEN > 2
  #define ROLL3SETUP  ROLL_PORT.DIRSET=ROLL3_DOWN_PIN | ROLL3_UP_PIN
  #define ROLL3_DOWN  ROLL_PORT.OUTCLR=ROLL3_UP_PIN   ; ROLL_PORT.OUTSET=ROLL3_DOWN_PIN
  #define ROLL3_UP    ROLL_PORT.OUTCLR=ROLL3_DOWN_PIN ; ROLL_PORT.OUTSET=ROLL3_UP_PIN
  #define ROLL3_OFF   ROLL_PORT.OUTCLR=ROLL3_DOWN_PIN ; ROLL_PORT.OUTCLR=ROLL3_UP_PIN
#endif // NUM_ROLLLADEN




